- name: checking variable priorities
  hosts: localhost
  vars:
    wishes: "Luck from play level vars"
  vars_files:
  - vars.yml
  vars_prompt:
  - name: wishes
    prompt: please enter wishes
    private: false
  tasks:
    - name: Printing Variables
      # vars:
      #   wishes: "Luck from task level vars"
      ansible.builtin.debug:
        msg: "Hi I'm Surya, Good {{wishes}}"

# 1st Priority Args
# 2nd Task Level
#