- name: checking variable priorities
  hosts: localhost
  # vars:
  #   wishes: "Luck from play level vars"
  vars_files:
  - vars.yml
  # vars_prompt:
  # - name: wishes
  #   prompt: please enter wishes
  #   private: false
  tasks:
    - name: Printing Variables
      # vars:
      #   wishes: "Luck from task level vars"
      ansible.builtin.debug:
        msg: "Hi I'm Surya, Good {{wishes}}"

# 1st Priority Args
# 2nd Task Level vars
# 3rd Vars files
# 4th Prompt vars
# 5th Play level vars
# 6th Inventory file vars
# 7th role level vars