- name: default value
  hosts: localhost
  tasks:
    - name: set default value
      ansible.builtin.debug:
        msg: "Hello {{name | default('Surya') }}"

#here name variable is not declared, but we set its default value as Surya

- name: lower to upper
  hosts: localhost
  vars:
    wishes: "happy new year 2025"
  tasks:
    - name: convert to upper
      ansible.builtin.debug:
        msg: "{{wishes | upper}}"

- name: upper to lower
  hosts: localhost
  vars:
    wishes: "HAPPY NEW YEAR 2025"
  tasks:
    - name: convert to lower
      ansible.builtin.debug:
        msg: "{{wishes | lower}}"

- name: find unique values
  hosts: localhost
  vars:
    numbers: [1,2,3,4,5,6,6,6,7,5,7,8,9,9,1,2]
  tasks:
      - ansible.builtin.debug:
          msg: "{{numbers | unique}}"

- name: find min and max
  hosts: localhost
  vars:
    age: [23,25,18,19,17,33,45,42,31,50]
  tasks:
    - ansible.builtin.debug:
        msg: "Minimum age: {{age | min}}, Maximum age: {{age | max}}"

- name: convert dictionary to list/items
  hosts: localhost
  vars:
    my_data:
      name: ganesh
      age: 29yrs
      gender: Male
  tasks:
    - ansible.builtin.debug:
        msg: "before converting: {{my_data}}"
    - ansible.builtin.debug:
        msg: "after converting: {{my_data | dict2items }}"

- name: convert items to dictionary
  hosts: localhost
  vars:
    my_list:
    - {'key': 'name', 'value': 'ganesh'}
    - {'key': 'age', 'value': '29yrs'}
    - {'key': 'gender', 'value': 'Male'}
  tasks:
    - ansible.builtin.debug:
        msg: "Items to dictionary: {{my_list | items2dict }}"