- name: loops
  hosts: localhost
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: "Hello {{item}}"
      loop:
      - ganesh
      - surya
      - manimohan

- name: install packages
  hosts: web
  #become: true
  tasks:
    - name: installing the packages
      ansible.builtin.dnf:
        name: "{{item}}"
        state: present
      loop:
      - nginx
      - fail2ban
      - lighttpd
