- name: install packages
  hosts: web
  become: true
  tasks:
    - name: installing the packages
      ansible.builtin.dnf:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
      - {name: 'nginx', state: 'latest'}
      - {name: 'fail2ban', state: 'absent'}
      - {name: 'lighttpd', state: 'absent'}
