- name: Configure Mysql-Server
  hosts: db
  vars:
    login_host: db.surya-devops.online
  become: true
  tasks:
    - name: Installing Mysql-Server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest
    - name: Start and Enable Mysql Service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: true

#to check if password is already setup or not
    - name: check DB connection
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: "{{login_host}}"
        filter: version
      ignore_errors: true
      register: mysql_output
    - name: print output
      ansible.builtin.debug:
        msg: "Output: {{mysql_output}}"
    # - name: setup root password
    #   ansible.builtin.command: mysql_secure_installation --set-root-pass {{password}}
    #   when: mysql_output.rc != 0
      

